[package]
name = "ray-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.21.3"
image = "0.24.3"
indicatif = "0.17.0"
nanorand = "0.7.0"
rayon = "1.5.3"
